### ISSUE TITLE
[Server]POST 일정등록 API 구현

### ISSUE THREAD

**Issue by hyunju-song** [codestates/medisharp-server#10]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: POST 일정등록 API 구현

### TODO
1. [x] Post Medicine API
2. [x] Post Schedules Common API 
3. [x] Post Schedules Date API
4. [x] Post Schedules_common_medicine API

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Urgency: `Middle`

ex)
POST req : 
{
일정이름 : 일정 
, 시간 : 시간 
,시작일자 : 시작 
,종료일자 : 종료 
,주기 : 주기
,약정보 : [{약이름A,T}, {약이름C,T}]  -> c
, 약정보B :  [ {약이름B, 약정보들}] -> w
}
