### ISSUE TITLE
[Server]GET 일정수정 페이지 API 구현

### ISSUE THREAD

**Issue by hyunju-song** [codestates/medisharp-server#11]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: GET 일정수정 페이지 API 구현

### TODO
1. [x] Search schedule_common Alarm to Edit/Delete -
2. [x] Get Clicked Day Checked/Time
3. [x] Get Clicked Day Medicine

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : = `server`
- Urgency:  `Middle`, `Low`

where  : userid , 일정이름, 클릭한 날짜
res : {클릭한 날짜+해당일정의 check 여부, 현재 일정이름, 일정에 등록된 약 이름, 시작, 종료,주기}
