### ISSUE TITLE
[Server]refactoring/API 코드 수정

### ISSUE THREAD

**Issue by hyunju-song** [codestates/medisharp-server#130]
### ISSUE
- Group:  `server`
- Type:  `feature`
- Detail: refactoring/API 코드 수정 
- 모든 API 코드들 점검하며 refactoring 필요(클라이언트와 병행해서 작업헤야함)
- TODO는 API 코드 점검하다가 수정 필요해서 작업하게된다면 추가하고 옆에 담당자 이름 기재한후 작업!

### TODO
1. [x] schedules-data/check/today api 응답통합
2. [x] schedules- data - month 관련 api 응답 통합
3. [ ] 일정등록 관련된 전반적인 코드 refactoring -> 진행 중 @hyunju-song 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Urgency: `High`
