### ISSUE TITLE
[Server] 약 정보 데이터 학습을 위한 이미지 데이터 준비 및 처리

### ISSUE THREAD

**Issue by hyunju-song** [codestates/medisharp-server#8]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 약 정보 데이터 학습 -> 이미지 분석 및 처리

### TODO
1. [x] 약 정보 데이터 download 및 sampling 
2. [x] 약 이미지 데이터 augmentation
3. [ ] 효과적인 학습을 위한 약 이미지 전처리
1) 알약 주변부 획득으로 그림자 제거,
2) 알약 영역 추출과 색, 흔들림 등 여러 효과로 data augmentation더 하기,
3) 글자부 획득(글자 인식을 학습; 할 수 있을진 모르겠음 ㅠ)

~~4. [ ] 약 정보 데이터 학습 -> 이미지 분석 및 처리~~(이게 issue #7 )

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group :  `server`
- Urgency:  `Middle`
